### PR TITLE
feat(CUST-PCI1): Adding and implementing put button for pet

### PR DESCRIPTION
**Pull request by Alexssuto**
JIRA: [Add Put For Pets (Team 2)](https://champlainsaintlambert.atlassian.net/browse/PCI-1?atlOrigin=eyJpIjoiMmY5MTI4YmUzNjA3NDcwZWFmYTY0ZDExOTkzOGI3MTYiLCJwIjoiaiJ9)
## Context:
This pull is about making an edit pet button that works. There was currently no way editing an existing pet. The point of this story was to add and implement an edit pet function 
## Changes
We added a new button to the customer page and implemented the code to edit them. It didn't quite work so it'll be a bug we fix on the next sprint.
## Before and After UI (Required for UI-impacting PRs)
Before
image
After
image
Project running on bash
image
Working on the scripts
Adding the button in owner detail html
image
Pet-Form Controller updates
image
Pet-form updates
image
Service Client Completion for Customer
image
Pet Service Put implementation
image
image
image

## Dev notes (Optional)
Still need to figure out why the update button isn't working properly yet. 
**Commits were done at the end. Dev forgot to commit as he was working on the project but will commit more in further sprints
## Linked pull requests (Optional)
- pull request link

### CODE REVIEW

**Review by Louenes099 — DISMISSED** [review]
Not enough screenshots of the project working and what has been done
Improper title for the pull request
Not enough commits for what has been done
Not enough information about the story and it's requirements

**Comment by DimitriDoo** [comment]
Need to merge this with main in order to work on my story.

**Review by DimitriDoo — APPROVED** [review]
The method "submitPetForm" in line 88 from pet-from.controller.js is never used, will need to change this later however the put method code in the services seems fine and the project still runs

**Comment by Louenes099** [comment]
Title is still not done correctly

**Review by dufourmax1738 — APPROVED** [review]
Everything looks good

**Pull request merged**
